[[redirects]]
  from = "/api/*"
  to = "https://script.google.com/macros/s/AKfycbz3wihhNFhZwtAneoPM79VDD2L8YfEvSOHd3UVHDMsgykhu1dw4Oiuayrk8DGJFU7Z3cw/exec"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
